In [6]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df=pd.read_csv("C:\\Users\\RABIN RESIN\\Desktop\\luminar\\development-journey\\mechine learning journey\\feature engineering\\student_data.csv.xls")
df.shape

(5000, 15)

In [8]:
df.head()

StudentID  Age  Gender  Ethnicity  ...  Music  Volunteering       GPA  GradeClass
0       1001   17       1          1  ...      0             0  3.158425           1
1       1002   18       1          2  ...      1             0  2.794655           2
2       1003   15       1          0  ...      0             1  3.774847           0
3       1004   17       1          0  ...      0             0  3.040574           1
4       1005   17       0          1  ...      0             0  3.382310           1

[5 rows x 15 columns]

In [9]:
df.columns

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')

In [10]:
df.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [11]:
df.dtypes

StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly        int64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass             int64
dtype: object

In [12]:
df["GPA"]=df["GPA"].astype("int")

In [13]:
df.dtypes

StudentID            int64
Age                  int64
Gender               int64
Ethnicity            int64
ParentalEducation    int64
StudyTimeWeekly      int64
Absences             int64
Tutoring             int64
ParentalSupport      int64
Extracurricular      int64
Sports               int64
Music                int64
Volunteering         int64
GPA                  int64
GradeClass           int64
dtype: object

In [14]:
df.drop(columns="StudentID",inplace=True)

In [15]:
df.columns

Index(['Age', 'Gender', 'Ethnicity', 'ParentalEducation', 'StudyTimeWeekly',
       'Absences', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports',
       'Music', 'Volunteering', 'GPA', 'GradeClass'],
      dtype='object')

In [16]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [17]:
X

Age  Gender  Ethnicity  ...  Music  Volunteering  GPA
0      17       1          1  ...      0             0    3
1      18       1          2  ...      1             0    2
2      15       1          0  ...      0             1    3
3      17       1          0  ...      0             0    3
4      17       0          1  ...      0             0    3
...   ...     ...        ...  ...    ...           ...  ...
4995   15       0          3  ...      1             0    4
4996   16       0          1  ...      0             0    2
4997   17       1          1  ...      0             1    4
4998   16       0          2  ...      1             0    4
4999   18       1          2  ...      0             1    2

[5000 rows x 13 columns]

In [18]:
Y

0       1
1       2
2       0
3       1
4       1
       ..
4995    0
4996    2
4997    0
4998    0
4999    3
Name: GradeClass, Length: 5000, dtype: int64

In [19]:
! pip install scikit-learn


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
! pip list

Package                 Version
----------------------- -----------
asgiref                 3.10.0
asttokens               3.0.1
colorama                0.4.6
comm                    0.2.3
contourpy               1.3.1
cycler                  0.12.1
debugpy                 1.8.19
decorator               5.2.1
distlib                 0.4.0
Django                  5.2.7
et_xmlfile              2.0.0
executing               2.2.1
filelock                3.20.3
fonttools               4.55.6
imbalanced-learn        0.13.0
imblearn                0.0
ipykernel               7.1.0
ipython                 9.9.0
ipython_pygments_lexers 1.1.1
jedi                    0.19.2
joblib                  1.4.2
jupyter_client          8.8.0
jupyter_core            5.9.1
kiwisolver              1.4.8
matplotlib              3.10.0
matplotlib-inline       0.2.1
mysql-connector-python  9.5.0
nest-asyncio            1.6.0
numpy                   2.2.2
openpyxl                3.1.5
packaging               24

In [21]:
from sklearn.preprocessing import MinMaxScaler

In [22]:
scaler=MinMaxScaler()

In [24]:
Xscale=scaler.fit_transform(X)
Xscale

array([[0.66666667, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.5       ],
       [1.        , 1.        , 0.66666667, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       ...,
       [0.66666667, 1.        , 0.33333333, ..., 0.        , 1.        ,
        1.        ],
       [0.33333333, 0.        , 0.66666667, ..., 1.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.66666667, ..., 0.        , 1.        ,
        0.        ]], shape=(5000, 13))

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test,Y_train,Y_test=train_test_split(Xscale,Y,test_size=0.2)

In [28]:
X_train

array([[0.33333333, 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.66666667, 0.        , 0.66666667, ..., 0.        , 1.        ,
        0.5       ],
       [0.        , 0.        , 0.66666667, ..., 1.        , 0.        ,
        0.5       ],
       ...,
       [0.        , 1.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.        , ..., 1.        , 0.        ,
        0.5       ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(4000, 13))

In [29]:
X_test

array([[0.33333333, 0.        , 1.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.66666667, 1.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       ...,
       [0.33333333, 1.        , 0.66666667, ..., 0.        , 0.        ,
        0.5       ],
       [0.33333333, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.33333333, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.5       ]], shape=(1000, 13))