In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split



In [2]:
df=pd.read_csv("C:\\Users\\RABIN RESIN\\Desktop\\luminar\\development-journey\\mechine learning journey\\feature engineering\\student_data.csv.xls")
df.shape

(5000, 15)

In [3]:
df.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [5]:
df.drop(columns="StudentID",inplace=True)

In [6]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [7]:
x

Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  Absences  \
0      17       1          1                  3               16        13   
1      18       1          2                  0               17        28   
2      15       1          0                  1               13        18   
3      17       1          0                  3                6         4   
4      17       0          1                  2                6        20   
...   ...     ...        ...                ...              ...       ...   
4995   15       0          3                  2               12        22   
4996   16       0          1                  2                1         2   
4997   17       1          1                  3               18        18   
4998   16       0          2                  2               15         0   
4999   18       1          2                  4                4        23   

      Tutoring  ParentalSupport  Extracurricular  Sports  Music  Volunteering  \
0            0                2                0       0      0             0   
1            0                2                1       1      1             0   
2            1                4                0       0      0             1   
3            0                3                1       0      0             0   
4            0                4                0       0      0             0   
...        ...              ...              ...     ...    ...           ...   
4995         0                2                0       1      1             0   
4996         0                2                0       1      0             0   
4997         1                0                1       0      0             1   
4998         0                2                1       1      1             0   
4999         0                0                1       0      0             1   

           GPA  
0     3.158425  
1     2.794655  
2     3.774847  
3     3.040574  
4     3.382310  
...        ...  
4995  4.000000  
4996  2.533415  
4997  4.000000  
4998  4.000000  
4999  2.000000  

[5000 rows x 13 columns]

In [8]:
y

0       1
1       2
2       0
3       1
4       1
       ..
4995    0
4996    2
4997    0
4998    0
4999    3
Name: GradeClass, Length: 5000, dtype: int64

In [9]:
scaler=MinMaxScaler()

In [10]:
xscale=scaler.fit_transform(x)

In [11]:
xscale

array([[0.66666667, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.57921267],
       [1.        , 1.        , 0.66666667, ..., 1.        , 0.        ,
        0.39732737],
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.88742329],
       ...,
       [0.66666667, 1.        , 0.33333333, ..., 0.        , 1.        ,
        1.        ],
       [0.33333333, 0.        , 0.66666667, ..., 1.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.66666667, ..., 0.        , 1.        ,
        0.        ]], shape=(5000, 13))

In [15]:
xtrain,xtest,ytrain,ytest=train_test_split(xscale,y,test_size=0.2)

In [16]:
xtest

array([[0.33333333, 0.        , 0.        , ..., 0.        , 1.        ,
        0.43110121],
       [0.66666667, 0.        , 0.33333333, ..., 0.        , 0.        ,
        0.3066344 ],
       [0.66666667, 0.        , 0.        , ..., 1.        , 1.        ,
        0.93914058],
       ...,
       [0.33333333, 0.        , 0.33333333, ..., 0.        , 0.        ,
        0.25393965],
       [0.33333333, 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 1.        , 0.        ,
        0.21735222]], shape=(1000, 13))

In [17]:
xtrain

array([[0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.6737036 ],
       [1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        1.        ],
       [1.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.73370728],
       ...,
       [0.33333333, 0.        , 0.        , ..., 1.        , 0.        ,
        0.10183511],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.95928437],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]], shape=(4000, 13))